development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://auoevdhdwpiwgq:36edfd4737bafe76f52b4dbbeb48de88ed3d3d73d8d735910e47bb5f469a5540@ec2-23-21-220-48.compute-1.amazonaws.com:5432/d3s4cp6g0otc2t
  channel_prefix: julinsecommerce_production
